  [[main]]
  name = "About"
  identifier = "About"
  weight = 100
  url = "/about2/"

  #[[main]]
  #name = "Projects"
  #weight = 200
  #identifier = "portfolio"
  #url = "/portfolio/"

  [[main]]
  name = "Research Output"
  weight = 300
  identifier = "publications"
  url = "/publications/" 

  [[main]]
  name = "Teaching"
  weight = 500
  identifier = "teaching"
  url = "/teaching/"

  [[main]]
  name = "Fellowships"
  weight = 400
  identifier = "fellowships"
  url = "/awards/" 

  #[[footer]]
  #name = "imprint"
  #weight = 1
  #identifier = "imprint"
  #url = "/imprint/"