
title = "Adhithiya Sivakumar"
author = "Adhithiya Sivakumar"
#copyright = "2020-2021"
description = "PhD Candidate, University of New Hampshire"
profilePicture = "images/adhi.jpg"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
#contactFormReCaptcha = "your-site-key-here"
# Google Fonts
#googleFonts = ["Indie+Flower", "Roboto:ital,wght@0,100;0,400;0,700;1,400"]
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
# readMore = true
# postSectionName = "blog"
# relatedPosts = true
# numberOfRelatedPosts = 3
# disableTitleCapitalization = true

reversepagetitle = true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'

# hidesidebar = true
contentratio = 0.725
displayMode = "dark"

[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

[plausibleAnalytics]
# domain = "example.com"
# serverURL = "https://analytics.example.com"

[umami]
# serverURL = "example.com"
# id = "94db1cb1-74f4-4a40-ad6c-962362670409"
# trackerScriptName = "mycustomscriptname.js"

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fa-brands' when brand icons, use 'fas' when standard solid icons.

[[socialIcons]]
icon = "fa-solid fa-envelope"
title = "e-mail"
url = "mailto:adhithiya.sivakumar@unh.edu"

[[socialIcons]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/Adhithya-235"

[[socialIcons]]
icon = "fa-solid fa-graduation-cap"
title = "Scholar"
url = "https://scholar.google.com/citations?user=yw2PqAQAAAAJ&hl=en"

[[socialIcons]]
icon = "fa-brands fa-orcid"
title = "OrcID"
url = "https://orcid.org/0000-0003-2691-5877"

[[socialIcons]]
icon = "fa-brands fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/adhithiya-sivakumar-b0b08411a/"


#[[socialIcons]]
#icon = "fa-brands fa-instagram"
#title = "instagram"
#url = "https://www.instagram.com/"



[mermaid]
# enable = true